name: Compile ReadTheDocs

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: copy to /srv/readthedocs
        run: cp -r $GITHUB_WORKSPACE /srv/readthedocs

      - name: Compile ReadTheDocs
        run: |
          cd /srv/readthedocs
          source venv/bin/activate
          make html