name: Compile ReadTheDocs

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile ReadTheDocs
        run: bash -c "cd /srv/readthedocs && source venv/bin/activate &&  make html"
